'use strict'

exports.GAME_FPS = 60
exports.NETWORK_FPS = 60

exports.MAP_TILE_SIZE = 128

exports.TIMER_SKIP_FACTOR = 10

exports.RUINS_WIDTH = 25
exports.RUINS_HEIGHT = 25
exports.RUINS_SIZE_PLAYERS_FACTOR = 1

exports.PLAYER_SIZE = 26
exports.PLAYER_ACCELERATION = .5
exports.PLAYER_MAX_SPEED = 10
exports.PLAYER_HP = 50
exports.PLAYER_HP_RECOVER_TIME = 500
exports.PLAYER_ACCELERATION_OFF = 0
exports.PLAYER_ACCELERATION_ON = 100

exports.PICKUP_NUM = 10
exports.PICKUP_NUM_PLAYERS_FACTOR = 1
exports.PICKUP_THRESHOLD = 20
exports.PICKUP_SCATTER = 300

exports.FLAME_SIZE = 8
exports.FLAME_MIN_SPEED = 5
exports.FLAME_MAX_SPEED = 15
exports.FLAME_TTL = 500
exports.FLAME_SPREAD = Math.PI/6
exports.FLAME_DELAY = 1000/50
exports.FLAME_NUM = 4
exports.FLAME_KNOCKBACK = .5
exports.FLAME_COLLIDE_TIMER = 1000/30

exports.DYNAMITE_SIZE = 14
exports.DYNAMITE_MIN_FUSE = 5000
exports.DYNAMITE_MAX_FUSE = 15000
exports.DYNAMITE_FUSE_SELECT_TIME = 750
exports.DYNAMITE_SPEED = 5
exports.DYNAMITE_FLAMES = 50
exports.DYNAMITE_FLAMES_TIME_FACTOR = 4
exports.DYNAMITE_FLAMES_SIZE = 16
exports.DYNAMITE_DAMAGE = 8
exports.DYNAMITE_DELAY = 5000

exports.INTERPOLATION_FRAMES = 1

exports.OCCLUSION_ALPHA = 1
exports.OCCLUSION_COLOR = '#c0e0f0'
